### ISSUE TITLE
SELF_SIGNED_CERT_IN_CHAIN

### ISSUE THREAD

**Issue by kantravigupta** [kantravigupta/MyNPMRepository#1]
I am facing problem while installing grunt. Showing error message - self signed certificate in certificate chain.
Also attaching the screen shot of the error messages. Please help.

Thanks
Ravi
![grunt_issue](https://cloud.githubusercontent.com/assets/1970472/19388515/bbe9b3b2-923d-11e6-88af-26929f023c02.png)

**Comment by kantravigupta** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\Projects\Personify.Web\Current\ThirdParty\Sass\nodejs\\node.exe',
1 verbose cli   'C:\Projects\Personify.Web\Current\ThirdParty\Sass\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'gulp' ]
2 info using npm@2.10.1
3 info using node@v0.12.4
4 verbose install initial load of C:\Users\ravi.gupta\AppData\Roaming\npm\package.json
5 verbose readDependencies loading dependencies from C:\Users\ravi.gupta\AppData\Roaming\npm\package.json
6 silly cache add args [ 'gulp', null ]
7 verbose cache add spec gulp
8 silly cache add parsed spec { raw: 'gulp',
8 silly cache add   scope: null,
8 silly cache add   name: 'gulp',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: '_',
8 silly cache add   type: 'range' }
9 silly addNamed gulp@_
10 verbose addNamed "_" is a valid semver range for gulp
11 silly addNameRange { name: 'gulp', range: '_', hasData: false }
12 silly mapToRegistry name gulp
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/gulp
16 verbose addNameRange registry:https://registry.npmjs.org/gulp not in flight; fetching
17 verbose request uri https://registry.npmjs.org/gulp
18 verbose request no auth needed
19 info attempt registry request try #1 at 5:04:31 PM
20 verbose request id 4000f7c95dc1e5ae
21 http request GET https://registry.npmjs.org/gulp
22 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
23 info attempt registry request try #2 at 5:04:42 PM
24 http request GET https://registry.npmjs.org/gulp
25 info retry will retry, error on last attempt: Error: self signed certificate in certificate chain
26 info attempt registry request try #3 at 5:05:43 PM
27 http request GET https://registry.npmjs.org/gulp
28 verbose stack Error: self signed certificate in certificate chain
28 verbose stack     at Error (native)
28 verbose stack     at TLSSocket.<anonymous> (_tls_wrap.js:929:36)
28 verbose stack     at TLSSocket.emit (events.js:104:17)
28 verbose stack     at TLSSocket._finishInit (_tls_wrap.js:460:8)
29 verbose cwd C:\Program Files (x86)\nodejs
30 error Windows_NT 6.1.7601
31 error argv "C:\Projects\Personify.Web\Current\ThirdParty\Sass\nodejs\\node.exe" "C:\Projects\Personify.Web\Current\ThirdParty\Sass\nodejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "gulp"
32 error node v0.12.4
33 error npm  v2.10.1
34 error code SELF_SIGNED_CERT_IN_CHAIN
35 error self signed certificate in certificate chain
36 error If you need help, you may report this error at:
36 error     https://github.com/npm/npm/issues
37 verbose exit [ 1, true ]
